from __future__ import annotations

from typing import Any, Final


DOC_BASE: Final = "https://docs.upbit.com/kr/reference"


def _doc(slug: str) -> str:
    return f"{DOC_BASE}/{slug}"


API_SURFACE: Final[dict[str, Any]] = {
    "exchange": "upbit",
    "documentation": {
        "api_reference_url": _doc("api-overview"),
        "api_reference_version": "v1.6.3",
        "checked_date": "2026-06-12",
        "notes": [
            "REST endpoints are listed one-to-one with Upbit's current API reference.",
            "No live account/trading request was executed during this surface check.",
        ],
    },
    "modules": {
        "rest": {
            "client": "src.exchanges.upbit.upbit_rest.UpbitRest",
            "source_file": "src/exchanges/upbit/upbit_rest.py",
            "base_url": "https://api.upbit.com",
            "implemented": {
                "from_info_yaml(file_path='info.yaml')": {
                    "category": "configuration",
                    "description": "Load upbit_api_key and upbit_secret_key.",
                },
                "from_config(source='auto', file_path='info.yaml')": {
                    "category": "configuration",
                    "description": "Load credentials from env, keyring, then info.yaml.",
                },
                "from_pocket_info_yaml(file_path='info.yaml', pocket_index=1)": {
                    "category": "configuration",
                    "description": "Load one of up to five Upbit Pocket API key pairs from info.yaml.",
                },
                "from_pocket_config(source='auto', file_path='info.yaml', pocket_index=1)": {
                    "category": "configuration",
                    "description": "Load Upbit Pocket credentials 1-5 from env, keyring, then info.yaml.",
                },
                "list_trading_pairs(is_details=False)": {
                    "category": "Quotation / Trading Pairs",
                    "auth": "none",
                    "method": "GET",
                    "endpoint": "/v1/market/all",
                    "doc": _doc("list-trading-pairs"),
                },
                "get_second_candles(ticker, to=None, count=200)": {
                    "category": "Quotation / Candle",
                    "auth": "none",
                    "method": "GET",
                    "endpoint": "/v1/candles/seconds",
                    "doc": _doc("list-candles-seconds"),
                },
                "get_minute_candles(ticker, unit=1, to=None, count=200)": {
                    "category": "Quotation / Candle",
                    "auth": "none",
                    "method": "GET",
                    "endpoint": "/v1/candles/minutes/{unit}",
                    "doc": _doc("list-candles-minutes"),
                },
                "get_day_candles(ticker, to=None, count=200, converting_price_unit=None)": {
                    "category": "Quotation / Candle",
                    "auth": "none",
                    "method": "GET",
                    "endpoint": "/v1/candles/days",
                    "doc": _doc("list-candles-days"),
                },
                "get_week_candles(ticker, to=None, count=200)": {
                    "category": "Quotation / Candle",
                    "auth": "none",
                    "method": "GET",
                    "endpoint": "/v1/candles/weeks",
                    "doc": _doc("list-candles-weeks"),
                },
                "get_month_candles(ticker, to=None, count=200)": {
                    "category": "Quotation / Candle",
                    "auth": "none",
                    "method": "GET",
                    "endpoint": "/v1/candles/months",
                    "doc": _doc("list-candles-months"),
                },
                "get_year_candles(ticker, to=None, count=200)": {
                    "category": "Quotation / Candle",
                    "auth": "none",
                    "method": "GET",
                    "endpoint": "/v1/candles/years",
                    "doc": _doc("list-candles-years"),
                },
                "get_trades(ticker, to=None, count=200, cursor=None, days_ago=None)": {
                    "category": "Quotation / Trade",
                    "auth": "none",
                    "method": "GET",
                    "endpoint": "/v1/trades/ticks",
                    "doc": _doc("list-pair-trades"),
                },
                "get_ticker(tickers)": {
                    "category": "Quotation / Ticker",
                    "auth": "none",
                    "method": "GET",
                    "endpoint": "/v1/ticker",
                    "doc": _doc("list-tickers"),
                },
                "get_quote_tickers(quote_currencies)": {
                    "category": "Quotation / Ticker",
                    "auth": "none",
                    "method": "GET",
                    "endpoint": "/v1/ticker/all",
                    "doc": _doc("list-quote-tickers"),
                },
                "get_orderbook(ticker, level=None, count=None)": {
                    "category": "Quotation / Orderbook",
                    "auth": "none",
                    "method": "GET",
                    "endpoint": "/v1/orderbook",
                    "doc": _doc("list-orderbooks"),
                },
                "get_orderbook_policy(tickers)": {
                    "category": "Quotation / Orderbook",
                    "auth": "none",
                    "method": "GET",
                    "endpoint": "/v1/orderbook/instruments",
                    "doc": _doc("list-orderbook-instruments"),
                },
                "get_orderbook_parse(ticker, count=5)": {
                    "category": "local helper",
                    "auth": "none",
                    "description": "Fetch and normalize top ask/bid orderbook levels.",
                },
                "get_accounts()": {
                    "category": "Exchange / Account",
                    "auth": "required",
                    "method": "GET",
                    "endpoint": "/v1/accounts",
                    "doc": _doc("all-accounts"),
                },
                "get_pocket()": {
                    "category": "Exchange / Pocket",
                    "auth": "required",
                    "method": "GET",
                    "endpoint": "/v1/pockets",
                    "doc": _doc("get-pocket-information"),
                },
                "list_pocket_api_keys(uuids=None, include_expired=None)": {
                    "category": "Exchange / Pocket",
                    "auth": "required",
                    "method": "GET",
                    "endpoint": "/v1/pockets/api_keys",
                    "doc": _doc("get-pocket-api-keys"),
                },
                "get_subpocket_accounts(uuid_value)": {
                    "category": "Exchange / Pocket",
                    "auth": "required",
                    "method": "GET",
                    "endpoint": "/v1/pockets/asset",
                    "doc": _doc("get-sub-pocket-balance"),
                },
                "create_main_pocket_transfer(to, currency, amount, from_uuid=None, identifier=None)": {
                    "category": "Exchange / Pocket",
                    "auth": "required",
                    "method": "POST",
                    "endpoint": "/v1/pockets/transfers",
                    "doc": _doc("post-universal-transfer"),
                },
                "list_main_pocket_transfers(...)": {
                    "category": "Exchange / Pocket",
                    "auth": "required",
                    "method": "GET",
                    "endpoint": "/v1/pockets/transfers",
                    "doc": _doc("get-universal-transfer"),
                },
                "create_subpocket_transfer(currency, amount, to=None, identifier=None)": {
                    "category": "Exchange / Pocket",
                    "auth": "required",
                    "method": "POST",
                    "endpoint": "/v1/pockets/transfers",
                    "doc": _doc("post-transfer"),
                },
                "list_subpocket_transfers(...)": {
                    "category": "Exchange / Pocket",
                    "auth": "required",
                    "method": "GET",
                    "endpoint": "/v1/pockets/transfers",
                    "doc": _doc("get-transfer"),
                },
                "place_order(...)": {
                    "category": "Exchange / Order",
                    "auth": "required",
                    "method": "POST",
                    "endpoint": "/v1/orders",
                    "doc": _doc("new-order"),
                },
                "test_order(...)": {
                    "category": "Exchange / Order",
                    "auth": "required",
                    "method": "POST",
                    "endpoint": "/v1/orders/test",
                    "doc": _doc("order-test"),
                },
                "cancel_order(uuid_value=None, identifier=None)": {
                    "category": "Exchange / Order",
                    "auth": "required",
                    "method": "DELETE",
                    "endpoint": "/v1/order",
                    "doc": _doc("cancel-order"),
                },
                "cancel_orders_by_ids(uuids=None, identifiers=None)": {
                    "category": "Exchange / Order",
                    "auth": "required",
                    "method": "DELETE",
                    "endpoint": "/v1/orders/uuids",
                    "doc": _doc("cancel-orders-by-ids"),
                },
                "cancel_all_orders(...)": {
                    "category": "Exchange / Order",
                    "auth": "required",
                    "method": "DELETE",
                    "endpoint": "/v1/orders/open",
                    "doc": _doc("batch-cancel-orders"),
                },
                "cancel_and_new_order(...)": {
                    "category": "Exchange / Order",
                    "auth": "required",
                    "method": "POST",
                    "endpoint": "/v1/orders/cancel_and_new",
                    "doc": _doc("cancel-and-new-order"),
                },
                "get_order(uuid_value=None, identifier=None)": {
                    "category": "Exchange / Order",
                    "auth": "required",
                    "method": "GET",
                    "endpoint": "/v1/order",
                    "doc": _doc("get-order"),
                },
                "list_orders_by_ids(ticker=None, uuids=None, identifiers=None, order_by=None)": {
                    "category": "Exchange / Order",
                    "auth": "required",
                    "method": "GET",
                    "endpoint": "/v1/orders/uuids",
                    "doc": _doc("list-orders-by-ids"),
                },
                "list_open_orders(...)": {
                    "category": "Exchange / Order",
                    "auth": "required",
                    "method": "GET",
                    "endpoint": "/v1/orders/open",
                    "doc": _doc("list-open-orders"),
                },
                "list_closed_orders(...)": {
                    "category": "Exchange / Order",
                    "auth": "required",
                    "method": "GET",
                    "endpoint": "/v1/orders/closed",
                    "doc": _doc("list-closed-orders"),
                },
                "get_order_chance(ticker)": {
                    "category": "Exchange / Order",
                    "auth": "required",
                    "method": "GET",
                    "endpoint": "/v1/orders/chance",
                    "doc": _doc("available-order-information"),
                },
                "get_withdraw_chance(currency, net_type=None)": {
                    "category": "Exchange / Withdrawal",
                    "auth": "required",
                    "method": "GET",
                    "endpoint": "/v1/withdraws/chance",
                    "doc": _doc("available-withdrawal-information"),
                },
                "list_withdraw_addresses(currency=None, net_type=None)": {
                    "category": "Exchange / Withdrawal",
                    "auth": "required",
                    "method": "GET",
                    "endpoint": "/v1/withdraws/coin_addresses",
                    "doc": _doc("list-withdrawal-addresses"),
                },
                "get_withdraw(uuid_value=None, txid=None, currency=None)": {
                    "category": "Exchange / Withdrawal",
                    "auth": "required",
                    "method": "GET",
                    "endpoint": "/v1/withdraw",
                    "doc": _doc("get-withdrawal"),
                },
                "list_withdraws(...)": {
                    "category": "Exchange / Withdrawal",
                    "auth": "required",
                    "method": "GET",
                    "endpoint": "/v1/withdraws",
                    "doc": _doc("list-withdrawals"),
                },
                "create_coin_withdraw(...)": {
                    "category": "Exchange / Withdrawal",
                    "auth": "required",
                    "method": "POST",
                    "endpoint": "/v1/withdraws/coin",
                    "doc": _doc("withdrawal-coin"),
                },
                "create_krw_withdraw(amount, two_factor_type)": {
                    "category": "Exchange / Withdrawal",
                    "auth": "required",
                    "method": "POST",
                    "endpoint": "/v1/withdraws/krw",
                    "doc": _doc("withdrawal-krw"),
                },
                "cancel_withdraw(uuid_value)": {
                    "category": "Exchange / Withdrawal",
                    "auth": "required",
                    "method": "DELETE",
                    "endpoint": "/v1/withdraws/coin",
                    "doc": _doc("cancel-withdrawal"),
                },
                "list_deposit_addresses(currency=None, net_type=None)": {
                    "category": "Exchange / Deposit",
                    "auth": "required",
                    "method": "GET",
                    "endpoint": "/v1/deposits/coin_addresses",
                    "doc": _doc("list-deposit-addresses"),
                },
                "get_deposit_address(currency, net_type)": {
                    "category": "Exchange / Deposit",
                    "auth": "required",
                    "method": "GET",
                    "endpoint": "/v1/deposits/coin_address",
                    "doc": _doc("get-deposit-address"),
                },
                "create_deposit_address(currency, net_type)": {
                    "category": "Exchange / Deposit",
                    "auth": "required",
                    "method": "POST",
                    "endpoint": "/v1/deposits/generate_coin_address",
                    "doc": _doc("create-deposit-address"),
                },
                "get_deposit(uuid_value=None, txid=None, currency=None)": {
                    "category": "Exchange / Deposit",
                    "auth": "required",
                    "method": "GET",
                    "endpoint": "/v1/deposit",
                    "doc": _doc("get-deposit"),
                },
                "list_deposits(...)": {
                    "category": "Exchange / Deposit",
                    "auth": "required",
                    "method": "GET",
                    "endpoint": "/v1/deposits",
                    "doc": _doc("list-deposits"),
                },
                "get_deposit_chance(currency, net_type)": {
                    "category": "Exchange / Deposit",
                    "auth": "required",
                    "method": "GET",
                    "endpoint": "/v1/deposits/chance/coin",
                    "doc": _doc("available-deposit-information"),
                },
                "create_krw_deposit(amount)": {
                    "category": "Exchange / Deposit",
                    "auth": "required",
                    "method": "POST",
                    "endpoint": "/v1/deposits/krw",
                    "doc": _doc("deposit-krw"),
                },
                "list_travel_rule_vasps()": {
                    "category": "Exchange / Travel Rule",
                    "auth": "required",
                    "method": "GET",
                    "endpoint": "/v1/travel_rule/vasps",
                    "doc": _doc("list-travelrule-vasps"),
                },
                "verify_travel_rule_by_deposit_uuid(deposit_uuid, vasp_uuid)": {
                    "category": "Exchange / Travel Rule",
                    "auth": "required",
                    "method": "POST",
                    "endpoint": "/v1/travel_rule/deposit/uuid",
                    "doc": _doc("verify-travelrule-by-uuid"),
                },
                "verify_travel_rule_by_deposit_txid(txid, currency, net_type, vasp_uuid)": {
                    "category": "Exchange / Travel Rule",
                    "auth": "required",
                    "method": "POST",
                    "endpoint": "/v1/travel_rule/deposit/txid",
                    "doc": _doc("verify-travelrule-by-txid"),
                },
                "list_wallet_statuses()": {
                    "category": "Exchange / Service",
                    "auth": "required",
                    "method": "GET",
                    "endpoint": "/v1/status/wallet",
                    "doc": _doc("get-service-status"),
                },
                "list_api_keys()": {
                    "category": "Exchange / Service",
                    "auth": "required",
                    "method": "GET",
                    "endpoint": "/v1/api_keys",
                    "doc": _doc("list-api-keys"),
                },
            },
            "compatibility_aliases": {
                "list_orders(...)": "Alias for list_orders_by_ids(...).",
                "list_deposit_allowed_assets(currency, net_type)": "Alias for get_deposit_chance(...).",
            },
            "not_public_api": {
                "tradeTest(client, test_ticker='usdt-krw')": "Manual live-test helper.",
                "orderbookTest(client, test_ticker='usdt-krw')": "Manual live-test helper.",
            },
            "missing": {},
        },
        "public_websocket": {
            "client": "src.exchanges.upbit.upbit_databank.UpbitPublicWebSocket",
            "source_file": "src/exchanges/upbit/upbit_databank.py",
            "auth": "none",
            "url": "wss://api.upbit.com/websocket/v1",
            "implemented": {
                "subscribe_orderbook(tickers, level=None)": {
                    "category": "Quotation / WebSocket",
                    "doc": _doc("websocket-orderbook"),
                },
                "subscribe_ticker(tickers)": {
                    "category": "Quotation / WebSocket",
                    "doc": _doc("websocket-ticker"),
                },
                "subscribe_trade(tickers)": {
                    "category": "Quotation / WebSocket",
                    "doc": _doc("websocket-trade"),
                },
                "subscribe_candle(tickers, interval='1m')": {
                    "category": "Quotation / WebSocket",
                    "doc": _doc("websocket-candle"),
                },
                "generic public stream": {
                    "methods": [
                        "connect()",
                        "send_request(request_types)",
                        "recv_once()",
                        "start_listen(on_message=None)",
                        "close()",
                    ],
                },
                "UpbitDataBank": {
                    "category": "local orderbook data collector",
                    "methods": ["start()", "stop(timeout_seconds=2.0)", "get_data(ticker=None)"],
                },
            },
            "missing": {},
        },
        "private_websocket": {
            "client": "src.exchanges.upbit.upbit_databank.UpbitMyOrder",
            "source_file": "src/exchanges/upbit/upbit_databank.py",
            "auth": "required",
            "url": "wss://api.upbit.com/websocket/v1/private",
            "implemented": {
                "subscribe_my_order(tickers=None)": {
                    "category": "Exchange / WebSocket",
                    "doc": _doc("websocket-myorder"),
                },
                "subscribe_my_asset()": {
                    "category": "Exchange / WebSocket",
                    "doc": _doc("websocket-myasset"),
                },
                "generic private stream": {
                    "methods": [
                        "from_info_yaml(file_path='info.yaml')",
                        "connect()",
                        "recv_once()",
                        "start_listen(on_message=None)",
                        "close()",
                    ],
                },
            },
            "missing": {},
        },
    },
}


__all__ = ["API_SURFACE"]
